grpc:
  netty-server:
    keep-alive-time: 30
    keep-alive-timeout: 10

  channel:
    test-server:
      address: '127.0.0.1'
      port: 9999
    rust-server:
      address: '127.0.0.1'
      port: 9998

server:
  port: 10000
  servlet:
      context-path: /test

logging:
  level:
    root: info
    org:
      springframework:
        security: error
        web: debug
    com:
      jasper: debug
    io:
      grpc: debug