grpc:
  netty-server:
    keep-alive-time: 30
    keep-alive-timeout: 10

  channel:
    test-server:
      address: 'java-server'
      port: 9999
    rust-server:
      address: 'rust-server'
      port: 9998

server:
  port: 10000
  servlet:
      context-path: /test

logging:
  level:
    root: info
    org:
      springframework:
        security: error
        web: debug
    com:
      jasper: debug
    io:
      grpc: debug