---
apiVersion: v1
kind: Service
metadata:
  name: java-client
  namespace: local-k8s  # Add namespace
spec:
  type: NodePort
  selector:
    app: java-client
  ports:
    - protocol: TCP
      port: 10000
      targetPort: 10000
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-client
  namespace: local-k8s  # Add namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-client
  template:
    metadata:
      labels:
        app: java-client
    spec:
      containers:
        - name: java-client
          image: java-client:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 10000